name: TaiXiu
author: Cortez_Romeo
version: '@version@'
main: com.cortezromeo.taixiu.TaiXiu
api-version: '1.21.4'
softdepend:
  - PlaceholderAPI
  - PlayerPoints
depend:
  - Vault
folia-supported: true
commands:
  taixiu:
    description: TaiXiu member commands
    aliases:
      - choitaixiu
      - playtaixiu
  taixiuadmin:
    description: TaiXiu admin commands
    aliases:
      - taixiuad
permissions:
  taixiu.use:
    description: Use TaiXiu player commands
    default: true
  taixiu.admin:
    description: Manage TaiXiu
    default: op
  taixiu.tax.bypass:
    description: Receive winnings without tax
    default: op
